<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Celine Park, Lauren Stiles">

<title>ENVS-193DS_final</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ENVS-193DS_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="ENVS-193DS_final_files/libs/quarto-html/quarto.js"></script>
<script src="ENVS-193DS_final_files/libs/quarto-html/popper.min.js"></script>
<script src="ENVS-193DS_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ENVS-193DS_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="ENVS-193DS_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ENVS-193DS_final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ENVS-193DS_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ENVS-193DS_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ENVS-193DS_final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="ENVS-193DS_final_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="ENVS-193DS_final_files/libs/tabwid-1.1.3/tabwid.js"></script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link active" data-scroll-target="#problem-1"><strong>Problem 1</strong></a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography"><strong>Bibliography</strong></a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2"><strong>Problem 2</strong></a></li>
  </ul></li>
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  <li><a href="#methods-1" id="toc-methods-1" class="nav-link" data-scroll-target="#methods-1">Methods</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#bibliography-1" id="toc-bibliography-1" class="nav-link" data-scroll-target="#bibliography-1">Bibliography</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ENVS-193DS_final</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Celine Park, Lauren Stiles </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>#load libraries:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1"><strong>Problem 1</strong></h2>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Small scale biotic disturbances can influence species compositions in plant communities (Bullock, 2000). In the Chihuahuan desert, kangaroo rat mounds can be classified as this type of small scale disturbance (Koontz and Simpson, 2010). Previous studies comparing landscapes containing kangaroo rat mounds have found that annual plant cover is higher on top of mounds than in surrounding areas (Davidson and Lightfoot, 2008). Though the literature outlines difference between vegetation composition, the scientific community still lacks understanding of how kangaroo rat mounds might influence seed bank composition (Koontz and Simpson, 2010). In this analysis, we aim to investigate this potential relationship. The question we want to answer is: How does total seed number differ between kangaroo rat mound locations? Our null hypothesis is that kangaroo rat mounds do not influence seed bank composition and our alternative hypothesis is that kangaroo rat mounds do influence seed bank composition.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>We read in the data available <a href="https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-sev.208.102459">here</a> (Koontz, T. and H. Simpson. 2013). We cleaned the data by selecting the columns we are interested in and renaming the locations (base of mound, edge of grass, grass inter-space) for more straightforward interpretation. We then added up all of the seed counts in each category since we are comparing total counts. We chose to use a Chi-squared analysis to compare the total seed counts in each category since this kind of test is useful for analyzing count data. Our data meets each of the assumptions required to run a Chi-squared test. Our data represents counts and the samples are independent. Individual counts can only fall in one category at a time since each count corresponds to a specific sampling site. Finally, each expected value for each cell was greater than 5. We tested the null hypothesis that sampling location does not significantly affect total seed count. The alternative hypothesis is that sampling location does influence total counts.</p>
<p>Read in data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>seed_dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/sev208_kratseedbank_20120213.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Clean data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create new data frame with kangaroo rat mound locations and seed numbers found </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>seed_dat_clean <span class="ot">&lt;-</span> seed_dat <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#select columns of interest</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">select</span>(loc, seeds) <span class="sc">|&gt;</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#remove "D" from loc column becuase there is no data defintion on the EDI portal </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">filter</span>(loc <span class="sc">!=</span> <span class="st">"D"</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#rename columns </span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">mutate</span>(<span class="at">loc =</span> <span class="fu">case_when</span>(loc <span class="sc">==</span> <span class="st">"B"</span> <span class="sc">~</span> <span class="st">"Base of mound"</span>, </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                                          loc <span class="sc">==</span> <span class="st">"E"</span> <span class="sc">~</span> <span class="st">"Edge of grass"</span>, </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                                          loc <span class="sc">==</span> <span class="st">"I"</span> <span class="sc">~</span> <span class="st">"Grass interspace"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">group_by</span>(loc) <span class="sc">|&gt;</span> </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">sum</span>(seeds)) <span class="sc">|&gt;</span> </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">column_to_rownames</span>(<span class="st">"loc"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#check for missing data </span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(seed_dat_clean) <span class="co">#no missing data </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ENVS-193DS_final_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check how many sampling events for each location </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>seed_dat_n <span class="ot">&lt;-</span> seed_dat <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">select</span>(loc, seeds) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">mutate</span>(<span class="at">loc =</span> <span class="fu">case_when</span>(loc <span class="sc">==</span> <span class="st">"B"</span> <span class="sc">~</span> <span class="st">"Base of mound"</span>, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                                          loc <span class="sc">==</span> <span class="st">"E"</span> <span class="sc">~</span> <span class="st">"Edge of grass"</span>, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                                          loc <span class="sc">==</span> <span class="st">"I"</span> <span class="sc">~</span> <span class="st">"Grass interspace"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">group_by</span>(loc) <span class="sc">|&gt;</span> </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">count</span>(loc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Run Chi-square Test:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>seed_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(seed_dat_clean)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>seed_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  seed_dat_clean
X-squared = 8106, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Visualization:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#reorganize seed_dat_clean so location is column name </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#rename columns </span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>seed_viz_dat <span class="ot">&lt;-</span> seed_dat_clean <span class="sc">|&gt;</span>  </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rownames_to_column</span>(<span class="st">"loc"</span>) </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#create bar graph to compare total seed counts at each location </span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>seed_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> seed_viz_dat, <span class="fu">aes</span>(<span class="at">x =</span> loc , <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"darkolivegreen4"</span>) <span class="sc">+</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sampling Location"</span>, </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> <span class="st">"Seed Count"</span>, </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"Total Number of Seeds Collected at each Sampling Location"</span>, </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">caption =</span> <span class="st">"Figure 1. Columns represent the total number of seeds collected."</span>) <span class="sc">+</span> </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>            <span class="co">#get rid of gap between bars and x axis </span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>            <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7000</span>),  <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>            <span class="co">#make plot look prettier</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Times New Roman"</span>),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#change size and location of plot caption</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>                  <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>), </span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#change size of plot title </span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>                  <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">15</span>), </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>                  <span class="co"># getting rid of gridlines</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>                  <span class="at">panel.grid =</span> <span class="fu">element_blank</span>()) </span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>                  <span class="co">#get rid of gap between bars and x axis)</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>seed_viz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ENVS-193DS_final_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Table 1: Total seed count data by sampling location</strong> Numbers in parentheses indicate the proportion of responses (the 6932 total seeds found at the base of kangaroo rat mounds make up 78 percent of the total seeds found at all locations, n = 1170).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate proportions</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>seed_summary <span class="ot">&lt;-</span> seed_dat_clean <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#make location column from rownames </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">rownames_to_column</span>(<span class="st">"Location"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#find total number of seeds from all locations sampled and make new column </span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sum =</span> <span class="fu">sum</span>(count)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#ungroup to make sure that distance groups don't mess up downstream functions</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate proportion of responses per living distance</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(<span class="at">prop =</span> count<span class="sc">/</span>sum) <span class="sc">%&gt;%</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co">#make a new column where counts and proportions are displayed together</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">paste0</span>(count, <span class="st">" ("</span>, <span class="fu">round</span>(prop, <span class="at">digits =</span> <span class="dv">2</span>), <span class="st">")"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co">#select columns of interest</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Location, text) <span class="sc">%&gt;%</span> </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co">#making the data frame wider so that the columns are responses and rows are distance</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"Location"</span>, <span class="at">values_from =</span> <span class="st">"text"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co">#turning everything into a table ----</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flextable</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co">#changing the column names to look nicer</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">distance =</span> <span class="st">"Living distance"</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>                    <span class="at">trails =</span> <span class="st">"Trails"</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                    <span class="at">dog_access =</span> <span class="st">"Dog access"</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>                    <span class="at">wildlife_habitat =</span> <span class="st">"Wildlife habitat"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="co">#making the table fit the viewer window</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autofit</span>()</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>seed_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div class="tabwid"><style>.cl-0434769e{}.cl-04305b4a{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-043278a8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-043281b8{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-043281c2{width:1.228in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-043281c3{width:1.44in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-043281c4{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-043281c5{width:1.228in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-043281cc{width:1.44in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-0434769e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-043281b8"><p class="cl-043278a8"><span class="cl-04305b4a">Base of mound</span></p></th><th class="cl-043281c2"><p class="cl-043278a8"><span class="cl-04305b4a">Edge of grass</span></p></th><th class="cl-043281c3"><p class="cl-043278a8"><span class="cl-04305b4a">Grass interspace</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-043281c4"><p class="cl-043278a8"><span class="cl-04305b4a">6932 (0.78)</span></p></td><td class="cl-043281c5"><p class="cl-043278a8"><span class="cl-04305b4a">1282 (0.14)</span></p></td><td class="cl-043281cc"><p class="cl-043278a8"><span class="cl-04305b4a">647 (0.07)</span></p></td></tr></tbody></table></div>
</div>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>Considering count data taken from the base of kangaroo rat mounds (n = 390), at the edge of grass mounds Bouteloua eripoda (n = 390), and in the inter-space between Bouteloua eripoda grass mounds (n = 390), total seed counts differ significantly by sampling location (Table 1. X-squared = 8106 (2), p = &lt; 2.2e-16, alpha = 0.05). We found that a large majority of seeds were collected at the base of the kangaroo rat mounds (78 percent), while significantly fewer seeds were found at locations beyond the kangaroo rat mounds (14 percent &amp; 7 percent). This result indicates that there are more seeds in the seed bank at the kangaroo rat mounds than in the seed bank below nearby Bouteloua eripoda grasses. We can reject the null hypothesis that sampling location has no effect on total seed count and conclude that kangaroo rat mounds have an effect on seed bank composition at this study site.</p>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography"><strong>Bibliography</strong></h2>
<p>Bullock, J. M. (2000) ‘Gaps and seedling colonization.’, CABI Books. CABI International. doi: 10.1079/9780851994321.0375.</p>
<p>Davidson, &amp; Lightfoot, D. C. (2008). Burrowing rodents increase landscape heterogeneity in a desert grassland. Journal of Arid Environments, 72(7), 1133–1145. https://doi.org/10.1016/j.jaridenv.2007.12.015</p>
<p>Koontz, T. and H. Simpson. 2013. Effects of Kangaroo Rat Mounds on Seed Banks of Grass and Shrublands at the Sevilleta National Wildlife Refuge, New Mexico (2001) ver 102459. Environmental Data Initiative.</p>
<p>Koontz and Simpson 2010, “The composition of seed banks on kangaroo rat (Dipodomysspectabilis) mounds in a Chihuahuan Desert grassland.” Journal of Arid Environments. https://doi.org/10.1016/j.jaridenv.2010.03.008</p>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2"><strong>Problem 2</strong></h2>
<p>Introduction:</p>
<p>load libraries</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(glmmTB) #not available </span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="introduction-1" class="level1">
<h1>Introduction</h1>
<p>Seed count can vary with plot type(shrub or open), plant species, or total number of inflorescence. Due to climate-change induced alterations, conditions in the alpine tundra have led to the expansion of woody shrubs known as “shrubification”.Shrubs are known to rapidly encroach on herbaceous plant communities in the tundra all over the world (Smith, 2011). Additionally, seed count varies with plant species and the total number of inflorescence. The “vigour” of seeds describes the sum total of their properties that establish seedlings to adapt based on a wide variety of factors (Mitchell, 2017) Knowing the variability within seeds across scales can help plants to adapt to climate change and elevated CO2, along with providing a path for enhancing crops (Mitchell, 2016).</p>
</section>
<section id="methods-1" class="level1">
<h1>Methods</h1>
<p>We cleaned the data by cleaning up the column names, but kept all the columns so as to help with the ggplot later on. We then created a graph with the missing variables, and chose to use a generalized linear model as our source of comparing the predictor variables to the total number of seeds. We then created multiple models to compare the seed count to the plot type, plant species, and total number of inflorescences. We determined which model to use by comparing AICc values, and visualized the data through a ggplot.</p>
<p>Read in data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>seedcount <span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/knb-lter-nwt.297.1/seedcount.csv"</span>)) <span class="sc">|&gt;</span> <span class="co">#reading in data </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">clean_names</span>()  <span class="co">#adjusting column names to lowercase </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Visualizing missing data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(seedcount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ENVS-193DS_final_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Building models</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear model, this is wrong</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>seedcount1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment, <span class="at">data =</span> seedcount)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># general linear model with Poisson distribution</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>seedcount2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment, <span class="at">data =</span> seedcount, <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>seedcoun2.a <span class="ot">&lt;-</span> <span class="fu">glm</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment, <span class="at">data =</span> seedcount, <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># general linear model with negative binomial distribution</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>seedcount3 <span class="ot">&lt;-</span> <span class="fu">glm.nb</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment, <span class="at">data =</span> seedcount)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#seedcount3.a &lt;- glmmTB(nr_seeds ~ total_nr_infl + plant_nr + tag_num, data = seedcount, family = "nbinom2") don't have packages</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co">#generalized linear model with Poisson distribution and random effect of site</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>seedcount4 <span class="ot">&lt;-</span> <span class="fu">glmer</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>shrub_num), <span class="at">data =</span> seedcount, <span class="at">family =</span> <span class="st">"poisson"</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co">#generalized linear model with negative binomial distribution and random effect of site</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>seedcount5 <span class="ot">&lt;-</span> <span class="fu">glmer.nb</span>(nr_seeds <span class="sc">~</span> total_nr_infl <span class="sc">+</span> species <span class="sc">+</span> treatment <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>shrub_num), <span class="at">data =</span> seedcount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Selecting the distribution to use</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>MuMIn<span class="sc">::</span><span class="fu">model.sel</span>(seedcount1, seedcount2, seedcount3, seedcount4, seedcount5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Model selection table 
            (Int) spc ttl_nr_inf trt       family    class init.theta link
seedcount3  1.918   +    0.07499   + NB(1.5049,l)   negbin        1.5  log
seedcount5  1.909   +    0.07498   + NB(1.5549,l) glmerMod                
seedcount1 -2.567   +    2.15000   +         g(i)       lm                
seedcount4  2.488   +    0.03145   +         p(l) glmerMod                
seedcount2  2.549   +    0.02989   +         p(l)      glm                
           random df    logLik   AICc   delta weight
seedcount3         9  -556.455 1132.0    0.00  0.717
seedcount5    s_n 10  -556.265 1133.8    1.86  0.283
seedcount1         9  -692.468 1404.0  272.03  0.000
seedcount4    s_n  9 -1058.768 2136.6 1004.62  0.000
seedcount2         8 -1150.107 2317.0 1185.09  0.000
Abbreviations:
 family: g(i) = 'gaussian(identity)', 
         NB(1.5049,l) = 'Negative Binomial(1.5049,log)', 
         NB(1.5549,l) = 'Negative Binomial(1.5549,log)', p(l) = 'poisson(log)'
Models ranked by AICc(x) 
Random terms: 
 s_n: 1 | shrub_num</code></pre>
</div>
</div>
<p>Model Summary</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>seedcount2 <span class="co">#calling seedcount2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = nr_seeds ~ total_nr_infl + species + treatment, 
    family = "poisson", data = seedcount)

Coefficients:
   (Intercept)   total_nr_infl   speciesCARRUP   speciesGEUROS   speciesKOBMYO  
       2.54931         0.02989        -2.19646        -0.75914         0.15451  
 speciesMINOBT   speciesTRIDAS  treatmentshrub  
      -0.14548         1.11376        -0.17174  

Degrees of Freedom: 181 Total (i.e. Null);  174 Residual
  (105 observations deleted due to missingness)
Null Deviance:      5094 
Residual Deviance: 1706     AIC: 2316</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(seedcount2) <span class="co">#creating a summary of the model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = nr_seeds ~ total_nr_infl + species + treatment, 
    family = "poisson", data = seedcount)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     2.5493104  0.0592232  43.046  &lt; 2e-16 ***
total_nr_infl   0.0298950  0.0006654  44.927  &lt; 2e-16 ***
speciesCARRUP  -2.1964550  0.1563725 -14.046  &lt; 2e-16 ***
speciesGEUROS  -0.7591403  0.0858719  -8.840  &lt; 2e-16 ***
speciesKOBMYO   0.1545097  0.0586618   2.634 0.008441 ** 
speciesMINOBT  -0.1454826  0.0648019  -2.245 0.024766 *  
speciesTRIDAS   1.1137639  0.1740224   6.400 1.55e-10 ***
treatmentshrub -0.1717363  0.0442661  -3.880 0.000105 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 5093.8  on 181  degrees of freedom
Residual deviance: 1705.8  on 174  degrees of freedom
  (105 observations deleted due to missingness)
AIC: 2316.2

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(seedcount2) <span class="co">#creating a confindence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %      97.5 %
(Intercept)     2.43185792  2.66403780
total_nr_infl   0.02859107  0.03120006
speciesCARRUP  -2.51534399 -1.90098452
speciesGEUROS  -0.92867474 -0.59188383
speciesKOBMYO   0.04016848  0.27016638
speciesMINOBT  -0.27240215 -0.01831202
speciesTRIDAS   0.75637192  1.44048917
treatmentshrub -0.25881162 -0.08526487</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r.squaredGLMM</span>(seedcount2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                R2m       R2c
delta     0.9388307 0.9388307
lognormal 0.9407220 0.9407220
trigamma  0.9368163 0.9368163</code></pre>
</div>
</div>
<p><strong>Table 1: Test statistics for predictor variables against total seed numbers</strong>. This table holds all the relevant information for the statistics of the predictor variables. The P-values are all less than .001, showing that the data is statistically significant, with the estimate, standard error, and statistic of each predictor variable are also shown.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model_squares_table <span class="ot">&lt;-</span> <span class="fu">tidy</span>(seedcount2) <span class="sc">%&gt;%</span>  <span class="co">#creating a flextable</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.value =</span> <span class="fu">case_when</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    p.value <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"&lt; 0.001"</span> <span class="co">#creating labels for the p-values</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">flextable</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">statistic =</span> <span class="st">"Statistic"</span>, <span class="co">#adjusting the titles of the columns</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">p.value =</span> <span class="st">"P-Value"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">std.error =</span> <span class="st">"Standard Error"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">estimate =</span> <span class="st">"Estimate"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">term =</span> <span class="st">"Term"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>model_squares_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div class="tabwid"><style>.cl-07edfa58{}.cl-07ead9cc{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-07ec1e2c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-07ec1e36{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-07ec262e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-07ec2638{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-07ec2639{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-07ec263a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-07ec2642{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-07ec2643{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-07edfa58"><thead><tr style="overflow-wrap:break-word;"><th class="cl-07ec262e"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">Term</span></p></th><th class="cl-07ec2638"><p class="cl-07ec1e36"><span class="cl-07ead9cc">Estimate</span></p></th><th class="cl-07ec2638"><p class="cl-07ec1e36"><span class="cl-07ead9cc">Standard Error</span></p></th><th class="cl-07ec2638"><p class="cl-07ec1e36"><span class="cl-07ead9cc">Statistic</span></p></th><th class="cl-07ec262e"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">P-Value</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">(Intercept)</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">2.54931038</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0592231577</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">43.045837</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">total_nr_infl</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.02989499</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0006654156</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">44.926796</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">speciesCARRUP</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-2.19645502</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.1563725046</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-14.046299</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">speciesGEUROS</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-0.75914034</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0858718650</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-8.840385</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">speciesKOBMYO</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.15450967</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0586618395</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">2.633904</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">speciesMINOBT</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-0.14548262</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0648018742</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-2.245037</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">speciesTRIDAS</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">1.11376389</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.1740224299</span></p></td><td class="cl-07ec263a"><p class="cl-07ec1e36"><span class="cl-07ead9cc">6.400117</span></p></td><td class="cl-07ec2639"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-07ec2642"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">treatmentshrub</span></p></td><td class="cl-07ec2643"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-0.17173633</span></p></td><td class="cl-07ec2643"><p class="cl-07ec1e36"><span class="cl-07ead9cc">0.0442660504</span></p></td><td class="cl-07ec2643"><p class="cl-07ec1e36"><span class="cl-07ead9cc">-3.879640</span></p></td><td class="cl-07ec2642"><p class="cl-07ec1e2c"><span class="cl-07ead9cc">&lt; 0.001</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Visualizing:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(seedcount2, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"total_nr_infl"</span>, <span class="st">"species"</span>, <span class="st">"treatment"</span>))  <span class="co">#creating predictors variable</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(seedcount, <span class="fu">aes</span>(<span class="at">x =</span> total_nr_infl, <span class="at">y =</span> nr_seeds)) <span class="sc">+</span> <span class="co">#putting total flowers as x-value, and total number of seeds as y</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> species), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co">#creating the species as points</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>treatment, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span> <span class="co">#adding the two types of shrubs</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">caption =</span> <span class="st">"Figure 1: Predictor Variables mapped against the total number of seeds"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Number of Seeds"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Total Number of Inflorescence Flowers"</span>) <span class="sc">+</span> <span class="co">#adding captions</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co">#adjusting theme</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="ENVS-193DS_final_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="results-1" class="level1">
<h1>Results</h1>
<p>After creating a Poisson regression with three predictor variables: plant species, open and closed shrub, and total number of inflorescence species, it was determined that the total number of inflorescence species has a significant impact on seed count (z-value = 44.927, and p-value &lt; 0.001), with an estimated coefficient of 0.030 (degrees of freedom = 181). The different species of plants (Carrup, Geuros, Minobt, Tridas) were all shown to have a significant effect on seed count (with all the p-values either being less than .001). Additionally, the treatment predictor variable was also shown to be statistically significant with an estimated coefficient of -0.172, and a p-value of less than .001. Thus, we can reject the null hypothesis that seed count does not have an effect on plant species, open and closed shrubs, and the total number of inflorescence species.</p>
</section>
<section id="bibliography-1" class="level1">
<h1>Bibliography</h1>
<p>Jack Mitchell and others, Variability in seeds: biological, ecological, and agricultural implications, Journal of Experimental Botany, Volume 68, Issue 4, 1 February 2017, Pages 809–817, https://doi.org/10.1093/jxb/erw397</p>
<p>Isla H Myers-Smith et al 2011 Environ. Res. Lett. 6 045509</p>
<p>Mitchell J, Johnston IG, Bassel GW. Variability in seeds: biological, ecological, and agricultural implications. J Exp Bot. 2017 Feb 1;68(4):809-817. doi: 10.1093/jxb/erw397. PMID: 27784726.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>